### ISSUE TITLE
What does emptiness mean for boolean values?

### ISSUE THREAD

**Issue by julienrf** [json4s/json4s-ast#10]
See https://github.com/json4s/json4s-ast/blob/master/jvm/src/main/scala/org/json4s/ast/safe/JValue.scala#L50

Note that this method is implemented the same way for all `JBoolean` implementations, so it is useless.

However, the extractor uses it: https://github.com/json4s/json4s-ast/blob/master/jvm/src/main/scala/org/json4s/ast/safe/JValue.scala#L56

**Comment by mdedetrich** [comment]
I believe its a stub that is needed just so that named extractors work (named extractors being a kinda hack to avoid boxing when you are pattern matching). Otherwise Scala won't detect it as a "named extractor", and it reverts to boxing. I could be wrong about this, I believe it this was suggested by @non (I had no idea named extractors existed before he mentioned it)

**Comment by julienrf** [comment]
Ok, but is `JBoolean` used as a named extractor anywhere? It seems that the current `unapply` returns an `Option`. BTW, returning an option is fine, but it should **not** return `isEmpty` (it should return `get`).

**Comment by mdedetrich** [comment]
Well if you pattern match with a JBoolean (i.e. `case JBoolean`) wouldn't that involve using a named extractor?

**Comment by julienrf** [comment]
No.

If you write the following:

``` scala
def isBoolean(jv: JValue): Boolean =
  jv match {
    case JBoolean(_) => true
    case _ => false
  }
```

It calls `JBoolean.unapply`, which uses the type `Option`.

“Named extractors” would be involved if `JBoolean.unapply` returned a `JBoolean` instead of an `Option[_]`.

BTW, the current behaviour is buggy because if you write the following:

``` scala
JTrue match {
  case JBoolean(b) => println(b)
}
```

It prints `false`.

**Comment by mdedetrich** [comment]
Ok cool, will fix this today

**Comment by mdedetrich** [comment]
I have fixed this, let me know if its still an issue

**Comment by julienrf** [comment]
Great.
