### ISSUE TITLE
Publish proper (i.e. not SNAPSHOT) versions

### ISSUE THREAD

**Issue by jrudolph** [json4s/json4s-ast#17]
The advantage is that real versions (regardless of the version number they get) can be depended on in downstream projects without having to worry that all potential users must include an extra repository.

**Comment by jrudolph** [comment]
Also, SNAPSHOT versions may be changed behind your back (even if that's not your intention).

**Comment by non** [comment]
:+1:

**Comment by mdedetrich** [comment]
Happy with a RC1 (don't want to do an actual release yet?)

**Comment by mdedetrich** [comment]
M1 has been released
