### ISSUE TITLE
reboot - add tests for other AST's

### ISSUE THREAD

**Issue by mdedetrich** [json4s/json4s-ast#6]
Since we have gone to the trouble of adding benchmark testing, we should compare ourselves to other `AST`'s to see how well `json4s-ast` performs in regards to construction/extraction. Initially this should be our contenders
1. Original `json4s-ast`
2. `argonaut`
3. `play-json`
4. `spray-json`
5. `lift-json`

Any others we should worry about?

**Comment by rossabaker** [comment]
I don't expect you'll bench much difference in simple construction, as they're all about the same.  (Exception: asympotic complexity of large collections, like `List`).  This seems like a more interesting metric for traversals, codecs, etc.

**Comment by mdedetrich** [comment]
Yeah I don't think this is needed, it was mainly a result of `@inline`, but it will probably end up being removed. Will also make the library harder to maintain, will close this for now
