### ISSUE TITLE
"Correct" representation of a Javascript number is a Double

### ISSUE THREAD

**Issue by mdedetrich** [json4s/json4s-ast#7]
Current representation of a `JNumber` is a `BigDecimal`, which implies an infinite precision real number. The javascript spec (http://stackoverflow.com/questions/3605925/does-javascript-have-double-floating-point-number-precision) specifies that a `Javascript` number is actually a 64 precision double, which is the exact same type as `Double`/`double` in `Scala`/`Java`. `Double` is also used in `Scala.js` to represent the `Javascript` number type (which is how I came across this)

For this reason, there may be an argument that having `JNumber` as a `Double` is more "correct" than `BigDecimal` (it will also have better performance). The downside is, that if you want to do maths on the `Double`, you will have to convert to a `BigDecimal` first if you want to do correct math operations

Thoughts?

**Comment by xuwei-k** [comment]
> "Correct" representation of a Javascript number is a Double

That is right. But I think json4s-ast is **JSON** AST for Scala, not JavaScript. Furthermore, JSON number is not same JavaScript number (JSON number is not limited).

http://stackoverflow.com/a/13502497

**Comment by mdedetrich** [comment]
Yeah, I got confused between `Javascript`/`JSON`, so it will remain a `BigDecimal`. Curiously then, how does one create a larger than 64bit representation of a number in `JSON` in `Javascript` if it doesn't have a larger precision number type?

Either way, closing this for now
